const data = [
    {"content": "https://www.etsy.com/listing/68055949/original-pet-portrait-in-pastel-in-8x10", "who_learned": "ryoung" },
    {"content": "https://www.etsy.com/listing/93803860/mad-cute-sad-fluffy-cat-neko-fluffiness", "who_learned": "nicoleg" },
    {"content": "http://i.imgur.com/W5Lek.jpg", "who_learned": "nicoleg" },
    {"content": "https://www.etsy.com/listing/68059397/giclee-of-original-largemouth-bass-fish", "who_learned": "nicoleg" },
    {"content": "https://www.etsy.com/listing/68401850/giclee-of-original-hippopotamus-painting", "who_learned": "nicoleg" },
    {"content": "i would totally crush that baby in mariokart", "who_learned": "nicoleg" },
    {"content": "https://www.etsy.com/listing/68055390/original-pet-portrait-in-pastel-in-11x14?image_id=216986637", "who_learned": "ryoung" },
    {"content": "https://www.etsy.com/listing/68058230", "who_learned": "ryoung" },
    {"content": "https://www.etsy.com/listing/68053363", "who_learned": "ryoung" },
    {"content": "https://www.etsy.com/listing/68051876", "who_learned": "ryoung" },
    {"content": "https://www.etsy.com/listing/84064857?image_id=279008372", "who_learned": "ryoung" },
    {"content": "https://www.etsy.com/listing/80096442", "who_learned": "nicoleg" },
    {"content": "http://s3-ec.buzzfed.com/static/enhanced/webdr01/2013/1/18/12/enhanced-buzz-32170-1358530914-19.jpg", "who_learned": "nicoleg" },
    {"content": "http://ecx.images-amazon.com/images/I/61F3zHFrB4L.jpg", "who_learned": "nicoleg" },
    {"content": "but guys.  beignets", "who_learned": "ccosentino" },
    {"content": "http://howfuckedismydatabase.com/nosql/fault-tolerance.png", "who_learned": "ryoung" },
    {"content": "RERN YIN", "who_learned": "ccosentino" },
    {"content": "i hate paypal and our code", "who_learned": "ross" },
    {"content": "http://i.imgur.com/XQNAla0.jpg", "who_learned": "ross" },
    {"content": "http://images.fineartamerica.com/images-medium-large/sad-brown-cat-jean-fitzhugh.jpg", "who_learned": "ryoung" },
    {"content": "https://img0.etsystatic.com/000/0/5560330/il_fullxfull.276236464.jpg?ref=l2", "who_learned": "nicoleg" },
    {"content": "https://img1.etsystatic.com/006/0/6891641/il_fullxfull.353062689_rxms.jpg?ref=l2", "who_learned": "nicoleg" },
    {"content": "http://www.etsy.com/listing/106501715", "who_learned": "ryoung" },
    {"content": "http://bukk.it/awesome.gif", "who_learned": "ryoung" },
    {"content": "http://s3-ec.buzzfed.com/static/2013-10/enhanced/webdr03/22/14/enhanced-buzz-32087-1382466200-4.jpg", "who_learned": "jeremy" },
    {"content": "http://www.etsy.com/listing/126654025", "who_learned": "ryoung" },
    {"content": "http://i.imgur.com/v5hRYbC.jpg", "who_learned": "boconnor" },
    {"content": "https://www.etsy.com/listing/111204885", "who_learned": "ryoung" },
    {"content": "http://i.imgur.com/nN3nZFr.png", "who_learned": "boconnor" },
    {"content": "\"There are one hundred people watching me summon douchecanoe.\"", "who_learned": "jeremy" },
    {"content": "http://fc04.deviantart.net/fs71/i/2011/029/8/3/emacs_user_at_work_by_earlcolour-d38aj2x.jpg", "who_learned": "ross" },
    {"content": "\"updated all giftcards with an expiration date of 13:00 April 2, 2037. Future generations can deal with our misdeeds.\"", "who_learned": "dmiller" },
    {"content": "http://et.sy/7f9qrh5", "who_learned": "jeremy" },
    {"content": "http://awesomegifs.com/wp-content/uploads/tech-support-baseball-bat-to-screen.gif", "who_learned": "tomtaki" },
    {"content": "http://postcaption.com/wp-content/uploads/2013/11/aww-yissss_aysww_0.jpg", "who_learned": "ryoung" },
    {"content": "http://media-cache-ec0.pinimg.com/736x/33/58/8c/33588c53aabc9001f9d7c66c58b1a1b6.jpg", "who_learned": "jeremy" },
    {"content": "http://i.imgur.com/JFz3718.png", "who_learned": "sbuckley" },
    {"content": "http://i.imgur.com/bl7yF6D.gif", "who_learned": "tomtaki" },
    {"content": "http://i.imgur.com/XHWrfkx.gif", "who_learned": "ross" },
    {"content": "http://media3.giphy.com/media/XGeCYPY7gwwso/200.gif", "who_learned": "nicoleg" },
    {"content": "Etsy Manifest Destiny", "who_learned": "jacob" },
    {"content": "https://www.etsy.com/listing/182511967/custom-made-animal-art", "who_learned": "boconnor" },
    {"content": "http://media.giphy.com/media/rYPD6KCyFymwE/giphy.gif", "who_learned": "jblossom" },
    {"content": "https://imgur.com/8PUukFa.png", "who_learned": "jeremy" },
    {"content": "http://www.strawberrywine.org/personal_images/gifarrific/eye_narrow.gif", "who_learned": "jeremy" },
    {"content": "http://erynsharp.files.wordpress.com/2014/03/suspicious.gif", "who_learned": "jeremy" },
    {"content": "https://38.media.tumblr.com/cc4f8c9f36d08ce1d5384458fd5bec99/tumblr_n98zahPR541sfnsayo2_250.jpg", "who_learned": "jeremy" },
    {"content": "http://media.giphy.com/media/2HavnYT1BfENa/giphy.gif", "who_learned": "tomtaki" },
    {"content": "http://burnersxxx.files.wordpress.com/2013/08/etsy-costumes.gif", "who_learned": "sbuckley" },
    {"content": "http://i.imgur.com/LWzQFfA.gif", "who_learned": "tomtaki" },
    {"content": "http://i.imgur.com/YbynzYf.gif", "who_learned": "jblossom" },
    {"content": "http://i.imgur.com/WGjCrGN.jpg", "who_learned": "tomtaki" },
    {"content": "http://giant.gfycat.com/UnrealisticRedArgusfish.gif", "who_learned": "tomtaki" },
    {"content": "http://lolkitten.org/wp-content/uploads/2013/03/funny-cats-lolcat-just-lion-here.jpg", "who_learned": "ross" },
    {"content": "http://i.imgur.com/TlP905h.gif", "who_learned": "tomtaki" },
    {"content": "http://i.imgur.com/qO3d4j1.gif", "who_learned": "tomtaki" },
    {"content": "It reads like poetry written by someone over thirty.", "who_learned": "ryoung" },
    {"content": "http://i.imgur.com/kQGOWwH.gif", "who_learned": "jblossom" },
    {"content": "http://i.imgur.com/5HFrl1J.gif", "who_learned": "jblossom" },
    {"content": "let’s roll the dics again", "who_learned": "sbuckley" },
    {"content": "let’s huddle up before our meeting with the tax team to get our story straight", "who_learned": "ryoung" },
    {"content": "https://imgur.com/JXADQ3t.png", "who_learned": "tomtaki" },
    {"content": "https://imgur.com/Eer6gCj.png", "who_learned": "jblossom" },
    {"content": "http://i.imgur.com/47DeS85.gifv", "who_learned": "tomtaki" },
    {"content": "i think i accidentally had a piece of tofu once", "who_learned": "jacob" },
    {"content": "http://i.imgur.com/ZgHBSH0.gifv", "who_learned": "ross" },
    {"content": "http://www.drroyspencer.com/wp-content/uploads/Kim-Jung-Un.jpg", "who_learned": "Richard" },
    {"content": "http://31.media.tumblr.com/tumblr_lax28wHoR71qcn8xuo1_500.gif", "who_learned": "ross" },
    {"content": "is that slang for some kind of drugs?", "who_learned": "sbuckley" },
    {"content": "http://gfycat.com/VelvetyWebbedHarpyeagle", "who_learned": "ross" },
    {"content": "http://i.imgur.com/1vvqdwS.gifv", "who_learned": "tomtaki" },
    {"content": "http://assets.sbnation.com/assets/2293859/kentuckygrampsdance.gif", "who_learned": "ross" },
    {"content": "http://c4.staticflickr.com/8/7598/16914999852_995b77a811_z.jpg", "who_learned": "ryoung" },
    {"content": "there are still balls left", "who_learned": "dschott" },
    {"content": "http://media.giphy.com/media/uO8Mn35ytbHm8/giphy.gif", "who_learned": "nicoleg" },
    {"content": "http://i.imgur.com/UghNeeC.jpg", "who_learned": "sbuckley" },
    {"content": "http://www.cakewrecks.com/storage/robbjon.ow.havedaymissinganice.jpg?__SQUARESPACE_CACHEVERSION=1386632241201", "who_learned": "jeremy" },
    {"content": "https://36.media.tumblr.com/94dfc845ae434d12ab207470e5371e1b/tumblr_nm78w1UuvX1qewacoo1_540.jpg", "who_learned": "jeremy" },
    {"content": "http://i.imgur.com/Om6wTBh.gif", "who_learned": "jblossom" },
    {"content": "http://i.imgur.com/whm75Vh.gif", "who_learned": "ryoung" },
    {"content": "http://i.imgur.com/Ycw0Y3s.gifv", "who_learned": "ross" },
    {"content": "someday our codebase will make sense ... but today is not that day", "who_learned": "sbuckley" },
    {"content": "http://img2.wikia.nocookie.net/__cb20140627152119/runescape/images/7/7c/Ruler_of_the_Ancient_Dead_Teleport.gif", "who_learned": "sbuckley" },
    {"content": "http://share.gifyoutube.com/ml15ZD.gif", "who_learned": "ryoung" },
    {"content": "the road to launching is paved with statements like \"one more field isn't too much of a big deal\"", "who_learned": "ryoung" },
    {"content": "http://i.imgur.com/cNpJyAQ.gifv", "who_learned": "tomtaki" },
    {"content": "http://i.imgur.com/r5V6CZl.jpg", "who_learned": "tomtaki" },
    {"content": "http://i.imgur.com/28LCrSm.gifv", "who_learned": "tomtaki" },
    {"content": "why can't I ever spell jerky right?", "who_learned": "Hailey" },
    {"content": "http://i.imgur.com/WKnQwiz.gifv", "who_learned": "ross" },
    {"content": "http://www.exocomics.com/comics/comics/292.jpg", "who_learned": "sbuckley" },
    {"content": "http://i.imgur.com/hMyedTi.gif", "who_learned": "jblossom" },
    {"content": "https://i.imgur.com/GGI0wZI.jpg", "who_learned": "steele" },
    {"content": "http://i.imgur.com/N6K4wnv.gif", "who_learned": "ross" },
    {"content": "http://i.imgur.com/m8nOy6S.gifv", "who_learned": "jblossom" },
    {"content": "http://i.ytimg.com/vi/m_OHn581OuE/hqdefault.jpg", "who_learned": "dschott" },
    {"content": "http://i.imgur.com/N6u0o2U.gifv", "who_learned": "ryoung" },
    {"content": "http://www.gifbin.com/bin/012013/1359571005_riding_tiny_bike.gif", "who_learned": "phu" },
    {"content": "https://www.youtube.com/watch?v=9ozbSx7PCKE", "who_learned": "sbuckley" },
    {"content": "http://i.imgur.com/ptDcgwo.gifv", "who_learned": "hailey" },
    {"content": "http://i.imgur.com/bUGsm6b.gifv", "who_learned": "hailey" },
    {"content": "https://imgur.com/OWPUkss.png", "who_learned": "phu" },
    {"content": "https://imgur.com/WpEYfjA.png", "who_learned": "sbuckley" },
    {"content": "http://blog.chosenmodels.com/wp-content/uploads/2014/10/RyanYoung-3975-copy.jpg", "who_learned": "Hailey" },
    {"content": "http://www.bellazon.com/main/uploads/monthly_08_2013/post-60960-0-82698100-1376251549.jpg", "who_learned": "Hailey" },
    {"content": "https://imgur.com/lRjFt3y.png", "who_learned": "sbuckley" },
    {"content": "https://imgur.com/oduiIw8.jpg", "who_learned": "tristan" },
    {"content": "https://imgur.com/u7lP1dF.jpg", "who_learned": "tristan" },
    {"content": "https://imgur.com/kYVhFHy.jpg", "who_learned": "tristan" },
    {"content": "http://i.imgur.com/RVldNA3.gifv", "who_learned": "sbuckley" },
    {"content": "http://49.media.tumblr.com/e1145c92f9597ad7686d3863cd73c29b/tumblr_nvx5ltUnaL1u0n985o1_500.gif", "who_learned": "sbuckley" },
    {"content": "http://49.media.tumblr.com/a3a6d09f29545887da3d9365f735cafc/tumblr_nry78aueUf1u0n985o3_500.gif", "who_learned": "sbuckley" },
    {"content": "who's responsible for this line of code ... i bet it was ph.u.  [runs git blame] nooooo, it was meeeeeee", "who_learned": "ryoung" },
    {"content": "I want to spend every moment I can with Tristan", "who_learned": "Hailey" },
    {"content": "Emacs has been replaced by a shell script which 1) Generates a syslog message at level LOG_EMERG; 2) reduces the user's disk quota by 100K; and 3) RUNS ED!!!!!!", "who_learned": "ryoung" },
    {"content": "if you are an Emacs, you should not be vi.", "who_learned": "sbuckley" },
    {"content": "http://i.imgur.com/S0JqQB0.gifv", "who_learned": "Hailey" },
    {"content": "I've been to a Coldplay concert. I had a great time.", "who_learned": "Hailey" },
    {"content": "https://gfycat.com/SecondhandBigheartedChafer", "who_learned": "Hailey" },
    {"content": "https://i.imgur.com/qa5uH3s.gifv", "who_learned": "Hailey" },
    {"content": "http://i.imgur.com/KArHPKB.gif", "who_learned": "steele" },
    {"content": "I got turned on to this podcast called Hardcore History", "who_learned": "Hailey" },
    {"content": "Ryan O'Donnell Young", "who_learned": "sbuckley" },
    {"content": "https://imgur.com/fjio8rc.jpg", "who_learned": "sbuckley" },
    {"content": "http://i.perezhilton.com/wp-content/uploads/2015/01/tumblr_ncvl0eyffl1qk08n1o4_r1_500.gif", "who_learned": "sbuckley" },
    {"content": "https://imgur.com/brllQi0.jpg", "who_learned": "sbuckley" },
    {"content": "http://gfycat.com/FastJovialBarebirdbat", "who_learned": "Hailey" },
    {"content": "http://i.imgur.com/lhHqCtu.gifv", "who_learned": "Hailey" },
    {"content": "my bracket will rise from the ashes like a basketball phoenix", "who_learned": "Hailey" },
    {"content": "i eat a lot so that i can become a large predator someday", "who_learned": "RichardMTG" },
    {"content": "i eat a lot so that i can become a large predator someday", "who_learned": "tristan" },
    {"content": "carol benson is an anagram of satoshi", "who_learned": "sbuckley" },
    {"content": "I can only handle so much social interaction in one day", "who_learned": "Hailey" },
    {"content": "https://media.giphy.com/media/xThuWlxLSgOxCuToNq/giphy.gif", "who_learned": "Hailey" },
    {"content": "https://imgur.com/OEW2jHe.jpg", "who_learned": "Hailey" },
    {"content": "http://i.imgur.com/qS6Si7h.gifv", "who_learned": "Hailey" },
    {"content": "https://imgur.com/iRaUoGK.jpg", "who_learned": "Richard" },
    {"content": "https://i.imgur.com/HUpozsc.gif", "who_learned": "jsaunders" },
    {"content": "http://i.imgur.com/76J4s2P.gifv", "who_learned": "ryoung" },
    {"content": "I'd link the tshirt design doc, but it appears to have devolved into a nsfw black hole", "who_learned": "RichardTrain" },
    {"content": "https://imgur.com/ISNI9z5.jpg", "who_learned": "ryoung" },
    {"content": "http://i.imgur.com/CTaEsDg.gif", "who_learned": "steele" },
    {"content": "http://i.imgur.com/dlXb1as.jpg", "who_learned": "jsaunders" },
    {"content": "I like my women how I like my weather: moist and unstable", "who_learned": "Hailey" },
    {"content": "https://i.reddituploads.com/e8812ef926d34835b94ccca1b32216c8?fit=max&h=1536&w=1536&s=fd6c539be53d9f68b24760fc599962e6", "who_learned": "Hailey" },
    {"content": "https://imgur.com/RRXygPV.jpg", "who_learned": "jeremy" },
    {"content": "https://imgur.com/TKbWN7d.jpg", "who_learned": "jeremy" },
    {"content": "https://imgur.com/FAGyVdo.jpg", "who_learned": "jeremy" },
    {"content": "https://i.redd.it/bnmtd6w9i15x.gif", "who_learned": "Hailey" },
    {"content": "\"Never trust WorldPay\"", "who_learned": "jbauman" },
    {"content": "https://s-media-cache-ak0.pinimg.com/736x/c9/29/e1/c929e1ae0e311b436954ef83cc8d7a21.jpg", "who_learned": "sbuckley" },
    {"content": "\"it's been really good to see you all do your jobs\"", "who_learned": "tristan" },
    {"content": "This man has thought more carefully and considerately about the use of socks in the Harry Potter books than you have ever thought about anything your miserable and lumpen-headed life. You disgust me.", "who_learned": "jeremy" },
    {"content": "\"Uh Oh, Canadians got paid twice\"", "who_learned": "tristan" },
    {"content": "http://i.imgur.com/QH04beN.png", "who_learned": "jsaunders" },
    {"content": "https://imgur.com/PFQCgQH", "who_learned": "toria" },
    {"content": "https://www.youtube.com/watch?v=Fc1P-AEaEp8", "who_learned": "sbuckley" },
    {"content": "https://github.etsycorp.com/Engineering/Etsyweb/blame/master/phplib/Billing/Controller/Payments.php#L146", "who_learned": "sbuckley" },
    {"content": "\"i was hitler neither time\"", "who_learned": "gilbert" },
    {"content": "https://i.imgur.com/e9xib0S.jpg", "who_learned": "gilbert" },
    {"content": "https://i.imgur.com/pWtsVHU.jpg", "who_learned": "samantha" },
    {"content": "i'm betting the original prompt was \"slow and steady wins the race\", and that's just how payments rolls to end up with \"it's a fucking turtle in a box\"", "who_learned": "samantha" },
    {"content": "https://i.imgur.com/Gj9m6M1.jpg", "who_learned": "samantha" },
    {"content": "https://i.redd.it/1sb4ia66x5301.png", "who_learned": "gilbert" }
];
